[phases.setup]
nixPkgs = ["python312", "ffmpeg-full", "gcc"]

[phases.install]
cmds = ["pip3 install -r requirements.txt"]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT --timeout 300 --workers 1"
